# Generated by Django 3.2.12 on 2023-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theverge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
