# Generated by Django 3.2.12 on 2023-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theverge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theverge',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='theverge',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theverge',
            name='headline',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='theverge',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
